import type { PlayerState } from '@/lib/save-source';

const MOCK_SKILL_LEVELS: Record<string, number> = {
  mining: 78,
  fishing: 92,
  woodcutting: 65,
  farming: 54,
  thieving: 40,
  firemaking: 88,
  smithing: 71,
  cooking: 60,
  fletching: 45,
  crafting: 50,
  runecrafting: 33,
  herblore: 38,
  construction: 42,
  agility: 61,
  mercantile: 29,
  prayer: 55,
  attack: 80,
  strength: 82,
  defense: 75,
  ranged: 67,
  magic: 58,
  hitpoints: 85,
  slayer: 63,
};

const MOCK_COMPLETED_QUEST_IDS = [
  'mining_1',
  'mining_2',
  'mining_3',
  'mining_4',
  'woodcutting_1',
  'woodcutting_2',
  'woodcutting_3',
  'fishing_1',
  'fishing_2',
  'fishing_3',
  'fishing_4',
  'fishing_5',
  'smithing_1',
  'smithing_2',
  'cooking_fish_1',
  'cooking_fish_2',
  'cooking_beef_1',
  'cooking_chicken_1',
  'cooking_mutton_1',
  'fletching_1',
  'fletching_2',
  'prayer_1',
  'prayer_2',
  'prayer_3',
  'combat_kills_1',
  'combat_kills_2',
  'combat_kills_3',
  'dungeon_farm_1',
  'dungeon_goblin_1',
  'mining_guild_1',
  'mining_guild_2',
  'fishing_guild_1',
  'fishing_guild_2',
  'fishing_guild_3',
];

const MOCK_IN_PROGRESS_QUESTS = [
  { questId: 'mining_5', progress: 340, completed: false },
  { questId: 'woodcutting_4', progress: 120, completed: false },
  { questId: 'smithing_3', progress: 45, completed: false },
  { questId: 'combat_kills_4', progress: 2100, completed: false },
];

const MOCK_ENEMY_KILLS: Record<string, number> = {
  sheep: 410,
  chicken: 380,
  cow: 260,
  giant_rat: 1200,
  goblin: 3400,
  skeleton: 880,
  zombie: 520,
  spider: 2000,
  bandit: 400,
  guard: 120,
  imp: 310,
  dark_wizard: 90,
  orc_warrior: 610,
  wild_monkey: 150,
  rogue: 40,
  knight: 30,
  troll: 180,
  hellhound: 220,
  fire_giant: 95,
  demon: 70,
  dragon: 25,
  lich: 14,
  glacial_mage: 60,
  frost_giant: 32,
  cave_troll: 140,
  shadow_thief: 75,
  will_o_wisp: 210,
  sea_serpent: 9,
  king_black_dragon: 26,
  demon_lord: 12,
  kraken: 8,
};

const MOCK_INVENTORY: Record<string, number> = {
  copper_ore: 1200,
  tin_ore: 950,
  iron_ore: 340,
  coal: 890,
  silver_ore: 120,
  gold_bar: 45,
  sapphire: 38,
  ruby: 12,
  oak_log: 640,
  raw_shrimp: 300,
  raw_trout: 220,
  raw_salmon: 180,
  raw_tuna: 90,
  raw_shark: 480,
  raw_beef: 75,
  raw_chicken: 60,
  feather: 2400,
  bones: 530,
  air_rune: 3000,
  water_rune: 1800,
  fire_rune: 2200,
  earth_rune: 1500,
  chaos_rune: 420,
  rune_essence: 5000,
  arrow_shaft: 1600,
  iron_arrow_tip: 400,
  potato_seed: 30,
  carrot_seed: 24,
  spider_silk: 55,
  carnival_ticket: 881,
};

const MOCK_SEEN_ITEMS = [
  ...Object.keys(MOCK_INVENTORY),
  'bronze_dagger',
  'bronze_sword',
  'bronze_scimitar',
  'iron_dagger',
  'iron_sword',
  'iron_scimitar',
  'steel_dagger',
  'steel_sword',
  'mithril_dagger',
  'dragon_longsword',
  'dragon_scimitar',
  'abyssal_whip',
  'trident_of_the_seas',
  'heirloom_pickaxe',
  'heirloom_axe',
  'heirloom_fishing_rod',
  'heirloom_hoe',
  'heirloom_frying_pan',
  'heirloom_greathammer',
  'mithril_full_helmet',
  'mithril_platebody',
  'mithril_platelegs',
  'mithril_boots',
  'mithril_arrow',
  'amulet_of_strength',
  'berserker_ring',
  'archers_ring',
];

const MOCK_LOADOUT_ARMOR = {
  head: 'mithril_full_helmet',
  body: 'mithril_platebody',
  legs: 'mithril_platelegs',
  boots: 'mithril_boots',
  necklace: 'amulet_of_strength',
  shield: null,
  signet: null,
};

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

export const MOCK_PLAYER_STATE: PlayerState = {
  exportedAt: Date.now() - 6 * HOUR,
  character: 'Aragorn',
  title: 'warlord',
  race: 'human',
  gender: 'male',
  combatLevel: 92,
  totalLevel: Object.values(MOCK_SKILL_LEVELS).reduce((a, b) => a + b, 0),
  skills: 23,
  questsCompleted: MOCK_COMPLETED_QUEST_IDS.length,
  questRows: MOCK_COMPLETED_QUEST_IDS.length + MOCK_IN_PROGRESS_QUESTS.length,
  enemiesKilled: Object.keys(MOCK_ENEMY_KILLS).length,
  seenItems: MOCK_SEEN_ITEMS.length,
  sessions: 2,
  coins: 1204553,
  carnivalTickets: MOCK_INVENTORY.carnival_ticket,
  slayerPoints: 59,
  ironman: true,
  flagsNote: null,
  raw: {
    skillLevels: MOCK_SKILL_LEVELS,
    skillXp: {},
    inventory: MOCK_INVENTORY,
    equipped: {
      weapon_atk: 'dragon_scimitar',
      weapon_str: 'heirloom_greathammer',
      weapon_ranged: 'maple_shortbow',
      weapon_magic: 'staff_of_fire',
      ...MOCK_LOADOUT_ARMOR,
      cape: 'mining_cape',
      ring: 'berserker_ring',
      pickaxe: 'heirloom_pickaxe',
      axe: 'heirloom_axe',
      fishing_rod: 'heirloom_fishing_rod',
      hoe: 'heirloom_hoe',
      frying_pan: 'heirloom_frying_pan',
    },
    pets: [
      { id: 'rock_golem', boostPercent: 10 },
      { id: 'forge_imp', boostPercent: 10 },
      { id: 'feather_drake', boostPercent: 5 },
      { id: 'timber_sprite', boostPercent: 10 },
      { id: 'herb_wisp', boostPercent: 5 },
      { id: 'ember_moth', boostPercent: 10 },
      { id: 'dragon_whelp', boostPercent: 5 },
      { id: 'imp_pet', boostPercent: 5 },
      { id: 'golden_goose', boostPercent: 10 },
      { id: 'baby_kraken', boostPercent: 5 },
    ],
    questProgress: [
      ...MOCK_COMPLETED_QUEST_IDS.map((questId) => ({ questId, completed: true })),
      ...MOCK_IN_PROGRESS_QUESTS,
    ],
    flags: {
      character_name: 'Aragorn',
      character_race: 'human',
      character_gender: 'male',
      equipped_title: 'warlord',
      slayer_points: 59,
      enemy_kills: MOCK_ENEMY_KILLS,
      seen_item_keys: MOCK_SEEN_ITEMS,
      ironman: true,
      skill_prestige: {
        mining: 2,
        fishing: 3,
        woodcutting: 1,
        firemaking: 2,
        smithing: 1,
        attack: 1,
        strength: 1,
        hitpoints: 4,
        ranged: 1,
        prayer: 1,
      },
      prestige_nodes: {
        mining: ['mining_xp_1', 'mining_xp_2', 'mining_yield_1', 'mining_gem_1'],
        smithing: ['smithing_flow_1', 'smithing_thrift_1'],
        ranged: ['ranged_prowess_1', 'ranged_quiver_1'],
        agility: ['agility_endurance_1'],
      },
      xp_boost_expires_at: Date.now() + 90 * DAY,
      prestige_xp_boosts: { mining: Date.now() + 26 * HOUR },
      active_blessing_key: 'sacred_grace',
      active_blessing_expires_at: Date.now() + 3 * DAY,
      guild_daily_tier_counts: {
        'mining:0': 2,
        'mining:1': 3,
        'mining:2': 2,
        'fishing:0': 2,
        'fishing:1': 3,
        'fishing:2': 4,
        'fishing:3': 5,
      },
      unlocked_titles: [
        'warlord',
        'master_angler',
        'master_miner',
        'flamekeeper',
        'devout',
        'marksman',
        'seasonal_sunspire_solstice_2026',
      ],
      town_building_tiers: {
        inn: 2,
        guild_hall: 2,
        queue_master: 1,
        garden: 1,
        church: 3,
        cape_rack: 1,
        fairgrounds: 1,
        chronos_spire: 1,
        artisans_workshop: 2,
        dock: 1,
      },
      tower_best_floor: 87,
      tower_milestones: [10, 20, 30, 40, 50, 60, 70, 80],
      monument_tier: 2,
      monument_fund: 0,
      seasonal_banners_earned: [
        {
          event_id: 'sunspire_solstice_2026',
          display_text: 'Participated in the Sunspire Solstice 2026',
          completed_at_ms: Date.now() - 30 * DAY,
        },
      ],
      heirloom_xp: {
        heirloom_pickaxe: 4_000_000,
        heirloom_fishing_rod: 6_500_000,
        heirloom_axe: 50_000,
        heirloom_hoe: 800_000,
        heirloom_frying_pan: 1_200_000,
        heirloom_greathammer: 2_300_000,
      },
      skilling_dungeon_notes: {
        copper_caverns: 5,
        abyssal_lagoon: 2,
        corrupted_canopy: 0,
        dwarven_depths: 6,
        shadow_vault: 1,
        shattered_spire: 0,
        sunken_grotto: 3,
        thieves_den: 4,
        whispering_grove: 0,
        crumbling_watchtower: 5,
      },
      elder_skill_levels: { attack: 45, strength: 50, defense: 40, hitpoints: 48, agility: 30 },
      elder_quests_completed: [],
      armor_loadouts: {
        attack: { ...MOCK_LOADOUT_ARMOR, cape: 'warriors_guild_cape', ring: 'berserker_ring' },
        strength: { ...MOCK_LOADOUT_ARMOR, cape: 'warriors_guild_cape', ring: 'berserker_ring' },
        ranged: { ...MOCK_LOADOUT_ARMOR, cape: 'ranged_cape', ring: 'archers_ring' },
        magic: { ...MOCK_LOADOUT_ARMOR, cape: 'magic_cape', ring: null },
      },
      active_weapon_slot: 'weapon_str',
      ranged_loadout_arrow_key: 'mithril_arrow',
      magic_loadout_spell_name: 'fire_blast',
      active_potion_key: 'super_strength_potion',
      equipped_food: { shark: 1, swordfish: 1, lobster: 1, tuna: 1 },
      hired_mercenaries: [
        { merc_id: 'thane_dawnbringer', expires_at: Date.now() + 2 * DAY },
        { merc_id: 'fenna_swiftarrow', expires_at: Date.now() + 2 * DAY },
      ],
    },
  },
};
