import type { PlayerState } from '@/lib/save-source';

const MOCK_SKILL_LEVELS: Record<string, number> = {
  mining: 78,
  fishing: 92,
  woodcutting: 65,
  farming: 54,
  thieving: 40,
  firemaking: 88,
  smithing: 71,
  cooking: 60,
  fletching: 45,
  crafting: 50,
  runecrafting: 33,
  herblore: 38,
  construction: 42,
  agility: 61,
  mercantile: 29,
  prayer: 55,
  attack: 80,
  strength: 82,
  defense: 75,
  ranged: 67,
  magic: 58,
  hitpoints: 85,
  slayer: 63,
};

const MOCK_COMPLETED_QUEST_IDS = [
  'mining_1',
  'mining_2',
  'mining_3',
  'mining_4',
  'woodcutting_1',
  'woodcutting_2',
  'woodcutting_3',
  'fishing_1',
  'fishing_2',
  'fishing_3',
  'fishing_4',
  'fishing_5',
  'smithing_1',
  'smithing_2',
  'cooking_fish_1',
  'cooking_fish_2',
  'cooking_beef_1',
  'cooking_chicken_1',
  'cooking_mutton_1',
  'fletching_1',
  'fletching_2',
  'prayer_1',
  'prayer_2',
  'prayer_3',
  'combat_kills_1',
  'combat_kills_2',
  'combat_kills_3',
  'dungeon_farm_1',
  'dungeon_goblin_1',
  'mining_guild_1',
  'mining_guild_2',
  'fishing_guild_1',
  'fishing_guild_2',
  'fishing_guild_3',
];

const MOCK_ENEMY_KILLS: Record<string, number> = {
  giant_rat: 120,
  goblin: 340,
  skeleton: 88,
  zombie: 52,
  bandit: 40,
  guard: 12,
  dark_wizard: 9,
  orc_warrior: 61,
  spider: 200,
  wild_monkey: 15,
  rogue: 4,
  knight: 3,
  hellhound: 22,
  troll: 18,
  demon: 7,
  dragon: 2,
  king_black_dragon: 6,
  demon_lord: 2,
};

const MOCK_SEEN_ITEMS = [
  'bronze_dagger',
  'bronze_sword',
  'bronze_scimitar',
  'iron_dagger',
  'iron_sword',
  'iron_scimitar',
  'steel_dagger',
  'steel_sword',
  'mithril_dagger',
  'dragon_longsword',
  'dragon_scimitar',
  'abyssal_whip',
  'trident_of_the_seas',
  'heirloom_pickaxe',
  'heirloom_axe',
  'heirloom_fishing_rod',
];

export const MOCK_PLAYER_STATE: PlayerState = {
  exportedAt: Date.now() - 6 * 60 * 60 * 1000,
  character: 'Aragorn',
  title: 'ranger_of_the_north',
  race: 'human',
  gender: 'male',
  combatLevel: 115,
  totalLevel: Object.values(MOCK_SKILL_LEVELS).reduce((a, b) => a + b, 0),
  skills: 23,
  questsCompleted: MOCK_COMPLETED_QUEST_IDS.length,
  questRows: 189,
  enemiesKilled: Object.keys(MOCK_ENEMY_KILLS).length,
  seenItems: MOCK_SEEN_ITEMS.length,
  sessions: 1,
  coins: 1204553,
  carnivalTickets: 881,
  slayerPoints: 59,
  flagsNote: null,
  raw: {
    skillLevels: MOCK_SKILL_LEVELS,
    skillXp: {},
    inventory: { raw_shark: 480, copper_ore: 1200, iron_ore: 340, coal: 90 },
    equipped: { weapon_atk: 'iron_sword', head: 'iron_full_helmet' },
    pets: [{ id: 'dragon_whelp' }, { id: 'imp_pet' }, { id: 'rock_golem' }, { id: 'golden_goose', boostPercent: 10 }],
    questProgress: MOCK_COMPLETED_QUEST_IDS.map((questId) => ({ questId, completed: true })),
    flags: {
      character_name: 'Aragorn',
      character_race: 'human',
      character_gender: 'male',
      equipped_title: 'ranger_of_the_north',
      slayer_points: 59,
      enemy_kills: MOCK_ENEMY_KILLS,
      seen_item_keys: MOCK_SEEN_ITEMS,
      skill_prestige: { mining: 2, fishing: 3, attack: 1, strength: 1, hitpoints: 4 },
      prestige_nodes: { mining: ['mining_xp_1', 'mining_xp_2'] },
      guild_daily_tier_counts: {
        'mining:0': 2,
        'mining:1': 3,
        'mining:2': 2,
        'fishing:0': 2,
        'fishing:1': 3,
        'fishing:2': 4,
        'fishing:3': 5,
      },
      unlocked_titles: ['ranger_of_the_north', 'master_miner', 'master_angler'],
      town_building_tiers: { inn: 2, guild_hall: 1, church: 3, fairgrounds: 1 },
      tower_best_floor: 87,
      tower_milestones: [10, 25, 50, 75],
      monument_tier: 2,
      monument_fund: 0,
      seasonal_banners_earned: [
        { event_id: 'sunspire_solstice', event_display_name: 'Sunspire Solstice', completed_at_ms: Date.now() },
      ],
      heirloom_xp: { heirloom_pickaxe: 4_000_000, heirloom_axe: 50_000 },
      skilling_dungeon_notes: {
        copper_caverns: 5,
        abyssal_lagoon: 2,
        corrupted_canopy: 0,
        dwarven_depths: 6,
        shadow_vault: 1,
        shattered_spire: 0,
        sunken_grotto: 3,
        thieves_den: 4,
        whispering_grove: 0,
        crumbling_watchtower: 5,
      },
    },
  },
};
