/**
 * Generated by scripts/sync-game-data.js. Do not edit by hand.
 *
 * Derived from the game's skilling_dungeons/*.json - every expedition's display name is
 * dropped in favor of humanize(key), except where they disagree (see EXPEDITION_LABEL_OVERRIDES).
 */

export const EXPEDITION_KEYS = [
  'abyssal_lagoon',
  'copper_caverns',
  'corrupted_canopy',
  'crumbling_watchtower',
  'dwarven_depths',
  'shadow_vault',
  'shattered_spire',
  'sunken_grotto',
  'thieves_den',
  'whispering_grove',
] as const;
